# Generated by Django 4.2.7 on 2023-11-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Under maintenance', 'Maintenance')], default='Free', max_length=18)),
                ('entry_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
    ]
