# Generated by Django 4.2.7 on 2023-12-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='delete_image2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='delete_image3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='delete_image4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='delete_image5',
            field=models.BooleanField(default=False),
        ),
    ]
