class RoomFields:
    fields = [
        "id",
        "number",
        "status",
        "quantity",
        "entry_date",
        "departure_date",
        "daily_rate",
        "total_value",
        "image",
        "image2",
        "delete_image2",
        "image3",
        "delete_image3",
        "image4",
        "delete_image4",
        "image5",
        "delete_image5",
        "full_url",
        "full_url2",
        "full_url3",
        "full_url4",
        "full_url5",
        "hotel",
        "guest",
        "created_at",
        "updated_at",
    ]
    read_only_fields = [
        "id",
        "created_at",
        "updated_at",
    ]
    extra_kwargs = {
        "image": {"write_only": True},
        "image2": {"write_only": True},
        "delete_image2": {"write_only": True},
        "image3": {"write_only": True},
        "delete_image3": {"write_only": True},
        "image4": {"write_only": True},
        "delete_image4": {"write_only": True},
        "image5": {"write_only": True},
        "delete_image5": {"write_only": True},
    }
