# Generated by Django 4.2.7 on 2023-12-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['created_at']},
        ),
    ]
