# Generated by Django 4.2.7 on 2023-11-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
