# Generated by Django 4.2.7 on 2023-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_aditional',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
