# Generated by Django 4.2.7 on 2023-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_aditional',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
