# Generated by Django 4.2.7 on 2023-11-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complemente',
            new_name='complement',
        ),
    ]
