# Generated by Django 4.2.7 on 2023-11-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField(null=True)),
                ('nationality', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('contact_aditional', models.CharField(max_length=11, null=True)),
                ('emergency_num', models.CharField(max_length=11)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
