# Generated by Django 4.2.7 on 2023-11-10 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField(null=True)),
                ('nationality', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('contact_aditional', models.CharField(blank=True, default='', max_length=11)),
                ('emergency_num', models.CharField(max_length=11)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
