# Generated by Django 4.2.7 on 2023-11-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='username',
        ),
    ]
