# Generated by Django 4.2.7 on 2023-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_guest_options_alter_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='contact_aditional',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
